Multiplyer1 = int(input("Enter two numbers that will be divided by your third number. what is your first number?:"))
Multiplyer2 = int(input("Second number?"))
Denominator = int(input("What will they be divided by?"))
He_will_divide_us = int(int(Multiplyer1 + Multiplyer2))
Has_been_divided = int(He_will_divide_us / Denominator)
print("Answer:" + "(" + str(Multiplyer1) + "+" + str(Multiplyer2) + ")" + "/" + str(Denominator) + "=" + str(Has_been_divided))